client-side:
	cd client && npm start

server-side:
	cd server && npm start

test-hardhat:
	cd smart-contracts && npx hardhat test

install-client:
	cd client && npm install
install-server:
	cd server && npm install

run:
	gnome-terminal -- make server-side
	gnome-terminal -- make client-side